name: Create ECS Task Definition (Dev)

on:
  push:
    branches:
      - dev  # Only trigger on pushes to the dev branch

jobs:
  create-task:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      # 3. Register task definition
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --family my-dev-task \  # Unique name for dev task
            --container-definitions '[
              {
                "name": "nodeapp",
                "image": "nodeapp:dev",  # Replace with your image
                "memory": 512,
                "cpu": 256,
                "essential": true
              }
            ]' \
            --requires-compatibilities FARGATE \
            --network-mode awsvpc \
            --cpu "256" \
            --memory "512"