name: Deploy to ECS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Register ECS task definition
      - name: Register ECS Task Definition
        run: |
          aws ecs register-task-definition \
              --family nodeapp \
              --container-definitions '[{
                  "name": "nodeapp",
                  "image": "nodeapp:dev",
                  "memory": 512,
                  "cpu": 256,
                  "essential": true
              }]' \
              --requires-compatibilities FARGATE \
              --network-mode awsvpc \
              --cpu "256" \
              --memory "512"