name: Create ECS Task Definition

on:
  push:
    branches:
      - main  # Replace with your branch

jobs:
  create-task-def:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Register task definition
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --family my-task-definition \
            --container-definitions '[
              {
                "name": "my-container",
                "image": "nginx:latest",  # Replace with your image
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  { "containerPort": 80, "hostPort": 80 }
                ]
              }
            ]' \
            --requires-compatibilities FARGATE \
            --network-mode awsvpc \
            --cpu "256" \
            --memory "512" \
            --execution-role-arn "arn:aws:iam::ACCOUNT_ID:role/ecsTaskExecutionRole"